table dMarcas
	lineageTag: 55a6f41d-f2c1-46c6-822e-37d341173da0

	column Código_Marca
		dataType: int64
		formatString: 0
		lineageTag: 4b5f60c1-d9c1-4624-b725-dc7f66507b28
		summarizeBy: none
		sourceColumn: Código_Marca

		annotation SummarizationSetBy = Automatic

	column Marca
		dataType: string
		lineageTag: b0e1eb14-c0fa-4435-9acd-f932c95ac81d
		summarizeBy: none
		sourceColumn: Marca

		annotation SummarizationSetBy = Automatic

	column Origem
		dataType: string
		lineageTag: b3b2d9c0-ea24-409a-ad27-15011626d959
		summarizeBy: none
		sourceColumn: Origem

		annotation SummarizationSetBy = Automatic

	partition dMarcas = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\Ana\Documents\Documents\Alura\Cursos\PBI-visualizando e analisando\Base_de_dados-Opuline.xlsx"), null, true),
				    Marcas_Sheet = Fonte{[Item="Marcas",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Marcas_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Código_Marca", Int64.Type}, {"Marca", type text}, {"Origem", type text}, {"Column4", Int64.Type}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Column4"})
				in
				    #"Colunas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

